# -*- coding: utf-8 -*-
"""RasberryPi_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PaN4FzAH2kW1YPZ7wf1SzjMbnswHInJ
"""

sudo apt update
sudo apt install python3-pip python3-opencv -y
pip3 install ultralytics pyserial flask
# 시리얼 권한 부여
sudo usermod -a -G dialout $USER

python3 riverbot_stream.py \
  --port /dev/ttyUSB0 --baud 115200 \
  --cam 0 --model final_best.pt \
  --host 0.0.0.0 —web-port 5000